# Generated by Django 2.0.8 on 2018-08-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('chatty_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattyuser',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partners.Partner'),
        ),
    ]
