# Generated by Django 2.0.8 on 2018-08-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatty_users', '0002_chattyuser_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattyuser',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partners.Partner'),
        ),
    ]
