# Generated by Django 2.0.8 on 2018-09-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatty_users', '0003_auto_20180827_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattyuser',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partners.Partner'),
        ),
    ]
