# Generated by Django 2.0.8 on 2018-08-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_diary',
            name='feeling',
            field=models.CharField(blank=True, choices=[('Joy', 'Joy'), ('Soso', 'Soso'), ('Sentimental', 'Sentimental'), ('Sad', 'Sad'), ('Angry', 'Angry')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chatty_users.ChattyUser'),
        ),
    ]
