# Generated by Django 2.0.8 on 2018-08-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20180827_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answer',
            old_name='answer',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='single_diary',
            name='feeling',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
