# Generated by Django 2.0.8 on 2018-08-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20180829_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_answer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='question',
            name='message',
            field=models.TextField(max_length=30),
        ),
    ]
